export const LIST_PRODUCTS = "LIST_PRODUCTS";
export const SORT_PRODUCTS = "SORT_PRODUCTS";

export const GET_PRODUCT = "GET_PRODUCT";
export const CREATE_PRODUCT = "CREATE_PRODUCT";
export const UPDATE_PRODUCT = "UPDATE_PRODUCT";
export const DELETE_PRODUCT = "DELETE_PRODUCT";

export const GET_USER_AUTH = "GET_USER_AUTH";

